### ISSUE TITLE
Verify cf-compliance

### ISSUE THREAD

**Issue by jonas-witthuhn** [tropos-car/tropos-pyrnet#7]
utilize cf-checker etc and work on issues

**Comment by hdeneke** [comment]
Adding outputs of CF-compliance checkers:
*  CF Checker/cfchecks
* IOOS compliance checker version 5.1./compliance-checker

[compliance-checker_acdd1.3_pyrnet_s2vsr_network_l1b.report.txt](https://github.com/tropos-car/tropos-pyrnet/files/14111655/compliance-checker_acdd1.3_pyrnet_s2vsr_network_l1b.report.txt)
[compliance-checker_cf1.8_pyrnet_s2vsr_network_l1b.report.txt](https://github.com/tropos-car/tropos-pyrnet/files/14111656/compliance-checker_cf1.8_pyrnet_s2vsr_network_l1b.report.txt)
[cfchecks_pyrnet_s2vsr_network_l1b.report.txt](https://github.com/tropos-car/tropos-pyrnet/files/14111665/cfchecks_pyrnet_s2vsr_network_l1b.report.txt)
